### ISSUE TITLE
Design: Footer position

### ISSUE THREAD

**Issue by AgentGhost** [AgentGhost/ShareMe#10]
Footer sollte fest am unteren Fensterrand sitzen in der webapp.
Bitte um Diskussion.

**Comment by n4bb12** [comment]
was meinst du damit? der footer ist ja immer unten

**Comment by AgentGhost** [comment]
Bei manchen Browsern scrollt der in den verdeckten Bereich, so dass die Buttons beim Aufruf der Seite abgeschnitten oder nicht sichtbar sind.
