### ISSUE TITLE
Add app icons

### ISSUE THREAD

**Issue by n4bb12** [AgentGhost/ShareMe#12]
https://developers.google.com/web/fundamentals/web-app-manifest/
https://caniuse.com/#search=manifest

**Comment by n4bb12** [comment]
@AgentGhost dafür benötigen wir ein Icon. Willst du eins aussuchen? https://www.flaticon.com/

**Comment by AgentGhost** [comment]
https://www.flaticon.com/free-icon/music_1058102#term=song%20book&page=1&position=10

**Comment by n4bb12** [comment]
Im Pull Request https://github.com/AgentGhost/ShareMe/pull/32 ist auch schon ein Manifest eingefügt worden, nur noch mit den Standard Angular Icons.

**Comment by n4bb12** [comment]
Hier kann man verschiedene Größen vom Icon generieren:
http://cthedot.de/icongen/

**Comment by n4bb12** [comment]
Hier kannst du die Icons noch optimieren, damit sie kleiner sind:
https://tinypng.com/

**Comment by n4bb12** [comment]
<a href="https://www.flaticon.com/free-icon/playlist_926375">
  <img src="https://image.flaticon.com/icons/svg/926/926375.svg" height="50">
</a>

<a href="https://www.flaticon.com/free-icon/guitar_1069328">
  <img src="https://image.flaticon.com/icons/svg/1069/1069328.svg" height="50">
</a>

<a href="https://www.flaticon.com/free-icon/playlist_980248">
  <img src="https://image.flaticon.com/icons/svg/980/980248.svg" height="50">
</a>

<a href="https://www.flaticon.com/free-icon/notes_1082735">
  <img src="https://image.flaticon.com/icons/svg/1082/1082735.svg" height="50">
</a>

<a href="https://www.flaticon.com/free-icon/playlist_488566">
  <img src="https://image.flaticon.com/icons/svg/488/488566.svg" height="50">
</a>

https://www.flaticon.com/categories/music

**Comment by AgentGhost** [comment]
![playlist 1](https://user-images.githubusercontent.com/4854049/44939185-9102c900-ad83-11e8-8256-4f859ecf20c3.png)

**Comment by AgentGhost** [comment]
prefer CC0 license
e.g. https://pixabay.com/de/hinweis-icon-symbol-anmelden-2389227/

**Comment by AgentGhost** [comment]
![](https://cdn.pixabay.com/photo/2017/06/10/07/24/note-2389227_960_720.png)

**Comment by AgentGhost** [comment]
![](https://cdn.pixabay.com/photo/2016/04/01/10/33/flat-cycles-1299936_960_720.png)
in red.

**Comment by AgentGhost** [comment]
![](https://cdn.pixabay.com/photo/2013/07/13/09/37/loudspeaker-155807_960_720.png)

**Comment by AgentGhost** [comment]
https://icons8.com/

**Comment by AgentGhost** [comment]
https://icons8.com/free-icons
https://icons8.com/welovesvg

**Comment by AgentGhost** [comment]
![sharmeicon2](https://user-images.githubusercontent.com/4854049/44958260-05517f80-aede-11e8-8801-73ba46eac9a6.png)

**Comment by AgentGhost** [comment]
![playlist 3](https://user-images.githubusercontent.com/4854049/44959206-2f5d6e80-aeeb-11e8-9102-a25337e600c3.png)
