### ISSUE TITLE
add symbols

### ISSUE THREAD

**Issue by AgentGhost** [AgentGhost/ShareMe#28]
Suche nach markanten Symbolen für share-button, copy-button, clear-button.
... gear ... star ... settings ... load ... save ...
https://material.io/tools/icons/?style=baseline
Diskussion eröffnet...

**Comment by n4bb12** [comment]
❔

**Comment by AgentGhost** [comment]
https://www.flaticon.com/free-icon/share_263130#term=social%20share&page=1&position=20

**Comment by AgentGhost** [comment]
![image](https://user-images.githubusercontent.com/4854049/44433820-3362c580-a5a8-11e8-9273-0be32117b280.png)

**Comment by n4bb12** [comment]
It would be better to link to the icons you would like to use. Icons have licenses and might require attribution. Also it's easier to find matching icons when they are linked.

**Comment by n4bb12** [comment]
Ist hier noch etwas offen?

**Comment by AgentGhost** [comment]
https://material.io/ erfüllt den Zweck weitgehen, also nein
