### ISSUE TITLE
share work-in-progress feedback

### ISSUE THREAD

**Issue by AgentGhost** [AgentGhost/ShareMe#36]
When the share-button got pressed, the smartphone is working a few seconds before the share-options pop up. How about getting feedback for this via a small rotation animation.

**Comment by n4bb12** [comment]
On my phone, share opens instantly.

**Comment by n4bb12** [comment]
Do you think the app is slow, or does the native share interface take so long to load?

**Comment by n4bb12** [comment]
What type of loading indicator do you have in mind?

**Comment by AgentGhost** [comment]
still an issue. let's talk about it

**Comment by AgentGhost** [comment]
rotating circle or as discussed in #35 Snackbar maybe
