### ISSUE TITLE
samsung browser doesnt load app

### ISSUE THREAD

**Issue by AgentGhost** [AgentGhost/ShareMe#48]
maybe restart needed or cache makes problems

**Comment by AgentGhost** [comment]
for now chrome is working, but any idea how to fix it? or should we wait till there is an update for angular.

**Comment by n4bb12** [comment]
The only way to fix it right now is to implement our own service worker.

There are more things that don't work well in Samsung, e.g. add-to-home-screen support is really bad.

Let's ignore the browser for now.

**Comment by AgentGhost** [comment]
i agree

**Comment by AgentGhost** [comment]
hopefully thats the only one for the moment

**Comment by n4bb12** [comment]
I think **Chrome** and **Safari** are the only browsers we really need to care about.

Mobile browser usage in Germany:

![2018-09-02 01_58_58-window](https://user-images.githubusercontent.com/6810177/44950877-da224e00-ae53-11e8-9a0b-6b66dcf37ffc.png)

**Comment by AgentGhost** [comment]
closed for now
