### ISSUE TITLE
Suche erweitern

### ISSUE THREAD

**Issue by AgentGhost** [AgentGhost/ShareMe#5]
Die Verzeichnisse sollen auch nach Titelwörtern durchsucht werden können. Habe mir überlegt, dass das auf einem anderen Tab passieren könnte? Bitte um Diskussion.

**Comment by n4bb12** [comment]
Sind Titelwörter irgendwelche tags? Z.B. aus dem Stichwortverzeichnis?

**Comment by AgentGhost** [comment]
ich glaub selber Tab wäre besser (geringere Ladezeiten). zwei Buchstaben hintereinander im Inputfeld könnten die Suche aktivieren.

**Comment by n4bb12** [comment]
Mir ist noch nicht klar war das macht. Du willst einfach nur nach allen Wörtern suchen können, die angezeigt werden?

**Comment by AgentGhost** [comment]
z.B. bei Input "danke" erscheinen die Vorschläge
"Loben 45 - Ich will dir danken"
"Iwdd! 56 - Danket, danket dem Herrn"

**Comment by n4bb12** [comment]
Ok, würde sowas wie https://items.projectceleste.com?q=divine+sword das
erfüllen? Kannst ja mal herumspielen wie sich die suche da anfühlt. Die
Ergebnisse können dann z.B in einer Liste als popover angezeigt werden.

**Comment by AgentGhost** [comment]
Diese Art ist perfekt! Fühlt sich gut an.

Popover ist super

**Comment by AgentGhost** [comment]
Mit der Erweiterung: Input "b4" zeigt einem an, was der Titel (bzw. name) von "Loben 4" ist und nicht von "Loben 40" oder "Loben 4321"
also die Freiwörtersuche soll nur in bestimmten Fällen aktiv sein: 

> zwei Buchstaben hintereinander im Inputfeld könnten die Suche aktivieren. bzw. wenn das erste Zeichen kein Buchstabe ist und sonst das zweite zeichen keine Zahl.

**Comment by n4bb12** [comment]
Also d.h. wenn es ein genauer Treffer ist, sollen teilweise Treffer nicht gezeigt werden.

**Comment by AgentGhost** [comment]
Doch das schon. Genaue Treffer sollten oben stehen, aber teilweise-Treffer trotzdem aufgelistet. 
Die Suchen-Funktion soll aber erst angestartet werden, wenn 
1. das erste Input-Zeichen keinem qualifier entspricht (z.B. nicht 'g' oder 'b')
2. das zweite Zeichen sonst keiner Zahl entspricht
3. spätestens das dritte vierte oder x-te Zeichen wieder ein Buchstabe ist.

**Comment by n4bb12** [comment]
Meinst du mit "Suchen-Function anstarten" die Vorschläge im Popover?

**Comment by n4bb12** [comment]
Ich glaube 3. ist nur ein theoretischer Fall. Kennst du ein Lied, wo das auftreten kann?

**Comment by n4bb12** [comment]
#### Wie sollen die Suchvorschläge sortiert werden?
- Alphabetisch
- Ähnlichkeit zur Eingabe

Eingabe:
Pet

Alphabetisch:
Paul
Peter

Ähnlichkeit zur Eingabe
Peter
Paul

#### Wonach soll sortiert werden?
- Buchkürzel (Qualifier)
- Buchname
- Liednummer
- Liedname

**Comment by n4bb12** [comment]
Noch eine Frage zur Darstellung.

![localhost_4200_ nexus 5x](https://user-images.githubusercontent.com/6810177/44617959-2f1afe80-a86d-11e8-80da-04e7032e7030.png)

Die Frage ist, wie bekommt man da noch sinnvoll Suchvorschläge angezeigt?
Diese Möglichkeiten fallen mir ein:

- Buttons während der Eingabe ausblenden, um mehr Platz zu schaffen
- App in Fullscreen anzeigen, um mehr Platz zu schaffen (keine Browserleiste)
- Titel während der Eingabe ausblenden, um mehr Platz zu schaffen

Das könnte dann z.B. so aussehen
![localhost_4200_ nexus 5x 1](https://user-images.githubusercontent.com/6810177/44617998-15c68200-a86e-11e8-9d3f-8063d0996158.png)

So würden wir immerhin mindestens 5 Suchvorschläge anzeigen können.

Die Browserleiste kann man im Chome Mobile Preview leider nicht ausblenden, aber dort könnte dann auch noch der Titel hin, oder wir zeigen bis zu 8 Suchvorschläge an.

**Comment by n4bb12** [comment]
Die Suchvorschläge würde ich so anzeigen, wie in den Beispielen hier:
https://material.angular.io/components/autocomplete/examples

**Comment by AgentGhost** [comment]
Ja

**Comment by n4bb12** [comment]
![](https://media.giphy.com/media/nFjDu1LjEADh6/giphy.gif)
