### ISSUE TITLE
some more color experimenting in and around songlistarea

### ISSUE THREAD

**Issue by AgentGhost** [AgentGhost/ShareMe#53]
relates to #35 
color contrast between songarea and the rest https://github.com/AgentGhost/ShareMe/issues/35#issuecomment-417027273
snackbar idea with undo function https://github.com/AgentGhost/ShareMe/issues/35#issuecomment-417049875

**Comment by AgentGhost** [comment]
https://github.com/AgentGhost/ShareMe/issues/35#issuecomment-417027273

**Comment by AgentGhost** [comment]
On mobile Version the Shareme title could sit in the background like a transparent watermark

**Comment by n4bb12** [comment]
I think this would not add any value and just make the text hard to read. Could you maybe post an image of your idea?

**Comment by AgentGhost** [comment]
no value
