### ISSUE TITLE
add white transparent background to app icon

### ISSUE THREAD

**Issue by AgentGhost** [AgentGhost/ShareMe#65]
for the app loading screen it should be white `#000000XX` for XX is a number between 00 and FF (e.g. 66)

**Comment by n4bb12** [comment]
![icon](https://user-images.githubusercontent.com/6810177/46307890-7e64f500-c5b8-11e8-939d-eed05f84959a.png)

**Comment by n4bb12** [comment]
![2018-10-01 20_31_00-window](https://user-images.githubusercontent.com/6810177/46308062-ee737b00-c5b8-11e8-9918-1ab02737ac56.png)

**Comment by AgentGhost** [comment]
looks good
like the rounded corners
