### ISSUE TITLE
reaktive Vorschau als dropdown-Auswahl

### ISSUE THREAD

**Issue by AgentGhost** [AgentGhost/ShareMe#7]
Es soll eine Vorschau geben, die live auf die Eingabe reagiert. Dropdown hätte ich mir vorgestellt, könnte aber auch anders gelöst werden.

**Comment by n4bb12** [comment]
Ist das dasslebe wie #5?

**Comment by AgentGhost** [comment]
Es gehört bestimmt zusammen. Sind aber zwei Arbeitsschritte oder?

**Comment by AgentGhost** [comment]
Closing in favor of #5
